name: Application Checks and Deployment

env:
  DOCKER_HUB_REPO: dockkonstantinakk/ta-devops-exam-demo

on:
  #push:
  pull_request:
    types: [opened, reopened]
jobs:
  test:
    name: Test code for style, lint and security
    runs-on: ubuntu-latest
    steps:
    - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo "üêß This job is now running on a ${{ runner.os }} server hosted by GitHub!"
    - run: echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install pycodestyle
    - name: Lint with pylint
    #lint check
      run: |
        python lint_test.py
    - name: Style with pycodestyle
    #style check
      run: |
        pycodestyle python-app.py
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  build:
    needs: test
    name: Build and publish image to Docker registry
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build image
      run: docker build -t $DOCKER_HUB_REPO:$(date '+%Y-%m-%d')-${GITHUB_SHA:0:8} .

    - name: Docker Login
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: dockkonstantinakk/ta-devops-exam-demo
      
    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
  deploy:
    needs: build
    name: Deploy image to Google Cloud
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
##### Google Cloud Authentication
    - uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    - name: setup Google Deploy
      uses: google-github-actions/deploy-cloudrun@v0
      with:
        service: ta-devops-exam-demo
        image: gcr.io/${{ env.GCP_PROJECT }}/ta-devops-exam-demo
        region: europe-central2-a
        env_vars: NAME="telerik-github-actions-2021"
